# Generated by Django 4.2.3 on 2023-07-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0003_persona_compania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='compania',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hola.compania'),
        ),
    ]
