# Generated by Django 4.2.3 on 2023-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0007_alter_persona_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=50)),
                ('caja', models.CharField(max_length=50)),
            ],
        ),
    ]
