# Generated by Django 4.2.3 on 2023-07-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0008_seguridadsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='seguridad_social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hola.seguridadsocial'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hola.compania'),
        ),
    ]
