# Generated by Django 4.2.3 on 2023-07-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0009_persona_seguridad_social_alter_persona_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='seguridad_social',
        ),
        migrations.DeleteModel(
            name='SeguridadSocial',
        ),
        migrations.AddField(
            model_name='persona',
            name='certificado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hola.certificado'),
        ),
    ]
