# Generated by Django 4.2.3 on 2023-07-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0010_certificado_remove_persona_seguridad_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='certificado',
        ),
        migrations.AddField(
            model_name='certificado',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hola.persona'),
        ),
    ]
