# Generated by Django 4.2.3 on 2023-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0012_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hobbies',
            field=models.ManyToManyField(to='hola.hobbies'),
        ),
    ]
